version: '3.1'
services:

#  test-rest-api-3:
#    build: .
#    container_name: test-rest-api-3
#    ports:
#      - "18080:8080"
#      - "18787:8787"
#    restart: always
#    depends_on:
#      - postgres

  postgres:
    image: postgres
    container_name: telros
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=telros
      - PGDATA=/data/telros
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "roman.s.popov@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge